<a href="https://colab.research.google.com/github/assiou349/DS_Case-Study/blob/main/case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1.2, 2.5,3.2,1.8])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.dtype)

float64


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.ndim)

1


In [7]:
a.size

4

In [8]:
a = np.array([1,2,4], dtype=float)

In [10]:
a.dtype

dtype('float64')

In [11]:
a = np.array([False, True], dtype=bool)

In [12]:
a.dtype

dtype('bool')

In [13]:
print(a.dtype)

bool


In [14]:
a = np.array({"a":"toto", "b":"tata"})

In [15]:
print(a.dtype)

object


In [16]:
#suite arthimetique de raison 1
a = np.arange(0, 10)

In [17]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [20]:
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [21]:
a = np.ones(5)

In [22]:
a

array([1., 1., 1., 1., 1.])

In [23]:
a = np.full(shape=5, fill_value= 3.5)

In [24]:
a

array([3.5, 3.5, 3.5, 3.5, 3.5])

In [25]:
a = np.full(shape=(3,4), fill_value=4)

In [26]:
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [28]:
from google.colab import drive

In [30]:
drive.mount('/content/mydrive')

Mounted at /content/mydrive


In [31]:
a = np.loadtxt("/content/mydrive/MyDrive/MIT_IDSS/WEEK_1/vecteur.txt", dtype=float)

In [32]:
print(a)

[ 4.  5.  8. 16. 68. 14. 35.]


In [33]:
lst = [1.2,3.1,4.5]
print(type(lst))

<class 'list'>


In [35]:
a = np.asarray(lst, dtype=float)

In [36]:
print(a)

[1.2 3.1 4.5]


In [37]:
print(a.dtype)

float64


In [38]:
np.append(a, 10)

array([ 1.2,  3.1,  4.5, 10. ])

In [39]:
a

array([1.2, 3.1, 4.5])

In [41]:
a = np.append(a, 10)

In [42]:
a

array([ 1.2,  3.1,  4.5, 10. ])

In [43]:
print(a)

[ 1.2  3.1  4.5 10. ]


In [46]:
b = np.delete(a, 2)

In [47]:
b

array([ 1.2,  3.1, 10. ])

In [48]:
a

array([ 1.2,  3.1,  4.5, 10. ])

In [49]:
a.resize(10)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [50]:
b.resize(10)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [51]:
a = np.array([1, 2,3,4])

In [52]:
a.resize(10)

In [53]:
a

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0])

In [55]:
x = np.array([1,2,3,4])
y = np.array([6,6,7,8])
z =  np.append(a, b)

In [56]:
z

array([ 1. ,  2. ,  3. ,  4. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1.2,
        3.1, 10. ])

In [57]:
z.delete(2)

AttributeError: 'numpy.ndarray' object has no attribute 'delete'

In [59]:
z = np.delete(z, 2)

In [60]:
v = np.array([1.2,7.4,4.2,8.5,6.3])

In [61]:
print(v)

[1.2 7.4 4.2 8.5 6.3]


In [62]:
print(v[:])

[1.2 7.4 4.2 8.5 6.3]


In [63]:
print(v[0])

1.2


In [64]:
print(v[v.size -1])

6.3


In [65]:
print(v[1:3])

[7.4 4.2]


In [66]:
print(v[:3])

[1.2 7.4 4.2]


In [67]:
print(v[2:])

[4.2 8.5 6.3]


In [68]:
print(v[-1])

6.3


In [70]:
print(v[-3:])

[4.2 8.5 6.3]


In [71]:
print(v[np.arange(3)])

[1.2 7.4 4.2]


In [72]:
np.arange(3)

array([0, 1, 2])

In [73]:
x = v[:3]

In [74]:
x

array([1.2, 7.4, 4.2])

In [75]:
type(x)

numpy.ndarray

In [76]:
b = np.array([False, True, False])
print(x[b])

[7.4]


In [77]:
print(x[x < 3])

[1.2]


In [78]:
print(np.extract(v<2, v))

[1.2]


In [79]:
print(np.max(v))

8.5


In [80]:
print(np.argmax(v))

3


In [81]:
v

array([1.2, 7.4, 4.2, 8.5, 6.3])

In [82]:
print(np.sort(v))

[1.2 4.2 6.3 7.4 8.5]


In [84]:
print(np.argsort(v))

[0 2 4 1 3]


In [85]:
a = np.array([1,2,2,1,1,2])
print(np.unique(a))

[1 2]


In [86]:
print(np.mean(v))

5.5200000000000005


In [87]:
print(np.percentile(v, 50))

6.3


In [88]:
print(np.sum(v))

27.6


In [89]:
print(np.cumsum(v))

[ 1.2  8.6 12.8 21.3 27.6]


In [90]:
x = np.array([1.2,1.3,1.0])
y = np.array([2.1,0.8,1.3])

In [91]:
print(x*y)

[2.52 1.04 1.3 ]


In [92]:
print(x+y)

[3.3 2.1 2.3]


In [93]:
b = x > y

In [94]:
print(b)

[False  True False]


In [95]:
a = np.array([True,True,False,True],dtype=bool)
b = np.array([True,False,True,False],dtype=bool)

In [96]:
np.logical_and(a, b)

array([ True, False, False, False])

In [97]:
np.logical_xor(a, b)

array([False,  True,  True,  True])

In [98]:
x = np.array([1.2,1.3,1.0])
y = np.array([2.1,0.8,1.3])

In [99]:
v = np.vdot(x,y)

In [100]:
v

np.float64(4.86)

In [101]:
print(np.sum(x*y))

4.86


In [103]:
n = np.linalg.norm(x)

In [104]:
n

np.float64(2.0322401432901573)

In [105]:
import math

In [106]:
print(math.sqrt(np.sum(x**2)))

2.0322401432901573


In [107]:
x = np.array([1,2,5,6])
y = np.array([2,1,7,4])

In [108]:
print(np.intersect1d(x,y))

[1 2]


In [109]:
print(np.union1d(x,y))

[1 2 4 5 6 7]


In [110]:
print(np.setdiff1d(x,y))

[5 6]


In [111]:
print(np.union1d(x, y))

[1 2 4 5 6 7]


In [112]:
print(np.setdiff1d(x,y))

[5 6]
